language: java
sudo: required
group: deprecated
script:
- java -version
- echo $JAVA_HOME
jdk:
- oraclejdk8
- openjdk8
notification:
  email:
    recipients:
    - tingzai.yang@gmail.com
    on_success: never
    on_failure: always

cache:
  directories:
  - $HOME/cache